const PRODUCTS = [
  {
    id: "f1",
    category: "filter",
    name: "Ethiopia Yirgacheffe Grade 1",
    origin: "Эфиопия • 250г",
    tag: "Мытая",
    description:
      "Лимонная вербена, спелый белый персик и нежный жасмин в сладком чайном послевкусии.",
    price: 14.5,
    image: "assets/menu/card1.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 9.0 },
      { name: "1000 г", extra: 19.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f2",
    category: "filter",
    name: "Kenya Nyeri Peaberry",
    origin: "Кения • 250г",
    tag: "Натуральная",
    description:
      "Сок черной смородины, ежевика, цедра грейпфрута. Плотная искристая структура напитка.",
    price: 16.0,
    image: "assets/menu/card2.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 10.0 },
      { name: "1000 г", extra: 21.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f3",
    category: "filter",
    name: "Colombia Geisha Honey",
    origin: "Колумбия • 250г",
    tag: "Анаэробная",
    description:
      "Клубничное суфле, мелисса, розовый перец. Эксклюзивный микролот чемпионского уровня.",
    price: 21.5,
    image: "assets/menu/card3.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 14.0 },
      { name: "1000 г", extra: 29.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f4",
    category: "filter",
    name: "Rwanda Nyamasheke Red",
    origin: "Руанда • 250г",
    tag: "Мытая",
    description:
      "Чёрный чай с сухофруктами, сушеное яблоко, карамель и чистый цитрусовый финиш.",
    price: 13.5,
    image: "assets/menu/card4.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 8.5 },
      { name: "1000 г", extra: 18.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f5",
    category: "filter",
    name: "Costa Rica Tarrazú Anaerobic",
    origin: "Коста-Рика • 250г",
    tag: "Вайлд",
    description:
      "Спелая корица, темная слива, сладкое красное яблоко и сиропистое округлое тело чашки.",
    price: 15.0,
    image: "assets/menu/card5.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 9.5 },
      { name: "1000 г", extra: 20.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f6",
    category: "filter",
    name: "Guatemala Huehuetenango",
    origin: "Гватемала • 250г",
    tag: "Мытая",
    description:
      "Молочный шоколад, спелый абрикос и миндаль. Сбалансированный ежедневный фильтр-кофе.",
    price: 13.0,
    image: "assets/menu/card6.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 8.5 },
      { name: "1000 г", extra: 17.5 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f7",
    category: "filter",
    name: "Burundi Kayanza Yeast F1",
    origin: "Бурунди • 250г",
    tag: "Натуральная",
    description:
      "Инжир, малина, темный виноград и пряности. Ферментация с винными культурными дрожжами.",
    price: 16.5,
    image: "assets/menu/card7.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 10.5 },
      { name: "1000 г", extra: 22.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f8",
    category: "filter",
    name: "Fjord Brew Signature Filter",
    origin: "Бленд • 250г",
    tag: "Бленд",
    description:
      "50% мытая Эфиопия + 50% мытая Кения. Идеальный баланс цитрусов и ягодного джема.",
    price: 12.0,
    image: "assets/menu/card8.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 7.5 },
      { name: "1000 г", extra: 16.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f9",
    category: "filter",
    name: "Panama Boquete Geisha",
    origin: "Панама • 250г",
    tag: "Мытая",
    description:
      "Цветы жасмина, бергамот, мандарин и тростниковый сахар. Премиальный редкий лот.",
    price: 24.0,
    image: "assets/menu/card3.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 16.0 },
      { name: "1000 г", extra: 34.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "f10",
    category: "filter",
    name: "Honduras Marcala Organic",
    origin: "Гондурас • 250г",
    tag: "Органик",
    description:
      "Красное яблоко, карамель, молочный орех и мягкая шелковистая текстура напитка.",
    price: 14.0,
    image: "assets/menu/card4.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 9.0 },
      { name: "1000 г", extra: 19.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "e1",
    category: "espresso",
    name: "Brazil Cerrado Dulce",
    origin: "Бразилия • 250г",
    tag: "Натуральная",
    description:
      "Жареный фундук, темный шоколад, карамель. Плотное кремовое тело эспрессо.",
    price: 11.5,
    image: "assets/menu/card2.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 7.0 },
      { name: "1000 г", extra: 15.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под эспрессо", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "e2",
    category: "espresso",
    name: "Ethiopia Guji Espresso",
    origin: "Эфиопия • 250г",
    tag: "Мытая",
    description:
      "Спелый персик, темный виноград, бергамот и выразительная цитрусовая сладость.",
    price: 14.0,
    image: "assets/menu/card1.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 9.0 },
      { name: "1000 г", extra: 19.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под эспрессо", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "e3",
    category: "espresso",
    name: "Fjord Dark Peak Espresso",
    origin: "Бленд • 250г",
    tag: "Бленд",
    description:
      "Смесь Бразилии и Гватемалы средней обжарки. Ореховая паста и какао в капучино.",
    price: 12.0,
    image: "assets/menu/card8.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 7.5 },
      { name: "1000 г", extra: 16.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под эспрессо", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "e4",
    category: "espresso",
    name: "Colombia Huila Supremo",
    origin: "Колумбия • 250г",
    tag: "Мытая",
    description:
      "Тростниковый сахар, красное яблоко, цедра апельсина и гладкая шоколадная база.",
    price: 13.0,
    image: "assets/menu/card6.jpg",
    sizes: [
      { name: "250 г", extra: 0 },
      { name: "500 г", extra: 8.5 },
      { name: "1000 г", extra: 17.5 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под эспрессо", extra: 0 },
      { name: "Подарочный тубус (+$3.00)", extra: 3.0 },
    ],
  },
  {
    id: "d1",
    category: "drip",
    name: "Drip Box: Fjord Explorer (10 шт)",
    origin: "Сет дрипов • 10 шт",
    tag: "Ассорти",
    description:
      "Набор из 5 ярких микролотов в удобном формате. Заваривайте в чашке в путешествиях.",
    price: 9.5,
    image: "assets/menu/card5.jpg",
    sizes: [
      { name: "10 шт", extra: 0 },
      { name: "20 шт", extra: 8.0 },
      { name: "30 шт", extra: 15.0 },
    ],
    grinds: [
      { name: "В коробке", extra: 0 },
      { name: "Подарочная лента (+$1.50)", extra: 1.5 },
      { name: "Кружка эмаль (+$6.00)", extra: 6.0 },
    ],
  },
  {
    id: "d2",
    category: "drip",
    name: "Drip Box: Ethiopia Floral (10 шт)",
    origin: "Эфиопия • 10 шт",
    tag: "Мытая",
    description:
      "Цветочные ноты, лемонграсс и сладкий персик в каждом отдельном дрип-пакете.",
    price: 10.5,
    image: "assets/menu/card1.jpg",
    sizes: [
      { name: "10 шт", extra: 0 },
      { name: "20 шт", extra: 9.0 },
      { name: "30 шт", extra: 17.0 },
    ],
    grinds: [
      { name: "В коробке", extra: 0 },
      { name: "Подарочная лента (+$1.50)", extra: 1.5 },
      { name: "Кружка эмаль (+$6.00)", extra: 6.0 },
    ],
  },
  {
    id: "d3",
    category: "drip",
    name: "Drip Box: Kenya Berry Wine (10 шт)",
    origin: "Кения • 10 шт",
    tag: "Натуральная",
    description:
      "Плотный, винный профиль с черной смородиной и спелой клюквой без кофемолки.",
    price: 11.0,
    image: "assets/menu/card2.jpg",
    sizes: [
      { name: "10 шт", extra: 0 },
      { name: "20 шт", extra: 9.5 },
      { name: "30 шт", extra: 18.0 },
    ],
    grinds: [
      { name: "В коробке", extra: 0 },
      { name: "Подарочная лента (+$1.50)", extra: 1.5 },
      { name: "Кружка эмаль (+$6.00)", extra: 6.0 },
    ],
  },
  {
    id: "d4",
    category: "drip",
    name: "Hand Pour Starter Kit",
    origin: "Аксессуары • 1 набор",
    tag: "Набор",
    description:
      "Керамическая воронка V60, пачка белых фильтров и 250г сезонного кофе Fjord Brew.",
    price: 32.0,
    image: "assets/menu/card7.jpg",
    sizes: [
      { name: "Стандарт", extra: 0 },
      { name: "С чайником (+$19.00)", extra: 19.0 },
      { name: "С весами (+$25.00)", extra: 25.0 },
    ],
    grinds: [
      { name: "В зёрнах", extra: 0 },
      { name: "Под фильтр", extra: 0 },
      { name: "Подарочный бокс (+$4.00)", extra: 4.0 },
    ],
  },
];
